# Site settings
author: Cedric
title: Breaking Through in Tech
header-img: img/home-bg.png
email: joaquin.cedric@gmail.com
copyright_name: Cedric
description: > # this means to ignore newlines until "baseurl:"
  Journey to becoming a Developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cedric-joaquin

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
